### ISSUE TITLE
UI broke after adding a alias expression to the schema

### ISSUE THREAD

**Issue by lu-zen** [edgedb/edgedb-ui#110]
Added a alias expression and the ui broke, returns this:

```js
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setLoadingTab')
    at t.<anonymous> (index.ts:761:13)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Qe (action.ts:68:19)
    at t._fetchData (action.ts:49:16)
    at t.u (wrapInAction.ts:94:19)
    at n (modelFlow.ts:77:14)
    at modelFlow.ts:157:56
    at new Promise (<anonymous>)
```

The expression is an array of enum values, like:
```
scalar type Status extending enum<open, close, locked>;

alias BadStatus := <array<Status>>[ Status.locked, Status.closed ];
```

this [line](https://github.com/edgedb/edgedb-ui/blob/e999c348a588643b3c58cd85a6baffd654fc58a7/shared/common/schemaData/index.ts#L398)

**Comment by jaclarke** [comment]
What version of EdgeDB are you using? This bug may have been fixed in this PR: https://github.com/edgedb/edgedb-ui/pull/94.

**Comment by lu-zen** [comment]
> What version of EdgeDB are you using? This bug may have been fixed in this PR: #94.

v2.9+b1d697b

**Comment by lu-zen** [comment]
Still happens in v2.12+5454e58

```js
create migration {
  create scalar type Status extending enum<open, closed, locked>;
  create alias BadStatus := <array<Status>>[ Status.locked, Status.closed ];
};
```
Schema explorer throws an error:
```
Uncaught (in promise) Error: unknown type: null
    at $d (index.ts:398:15)
    at t.<anonymous> (database.ts:233:13)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at Qe (action.ts:68:19)
    at t.fetchSchemaData (action.ts:49:16)
    at t.u (wrapInAction.ts:94:19)
    at n (modelFlow.ts:77:14)
```
